server:
  servlet:
    context-path:
  port: 63070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taichi_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# minIO配置
minio:
  endpoint: http://127.0.0.1:9005     # MinIO服务地址
  fileHost: http://127.0.0.1:9000     # 文件地址host
  bucketName: taichibucket            # 存储桶bucket名称
  accessKey: admin                    # 用户名
  secretKey: 12345678                 # 密码

jwt:
  secret: mySecretKey
  expiration: 86400